//hugi-internes index-erzeugprogramm
//--- diese version konvertiert die indexdaten in ein array, der in h-file
//--- gespeichert werden kann!

#include <stdio.h>
#include "adalloc.h"

void main(int argc,char **argv)
{
  FILE *txtfile,
       *idxfile;
  long length,
       tempoffset;
  int  tempchar,
       i;

  char *index_names [200];
  long index_offsets[256],
       index_lengths[256],
       tempcounter,
       blahcounter,
       counter_index       =0;

  //speicher fÅr index_names reservieren
  for(tempcounter=0;tempcounter<200;tempcounter++)
    mymalloc((void *)&index_names[tempcounter],256,-1);

  //kommandozeile ok?
  if(argc!=3)
  {
    printf("error: zu viele/wenige kommandozeilenparameter\n"
           "syntax: index idxfile.ext hfile.ext\n");
    exit(1);
  }

  //txtfile îffnen
  if(NULL==(txtfile=fopen(argv[1],"rb")))
  {
    printf("error: textfile nicht vorhanden\n");
    exit(1);
  }

  //indexfile "durchlesen"
  while(254!=fgetc(txtfile)); //-> erstes ascii 254 Åberspringen
  do
  {
    tempcounter=0;
    while( 254!=(tempchar=fgetc(txtfile)) )
    {
      index_names[counter_index][tempcounter]=tempchar;
      tempcounter++;
    }
    index_names[counter_index][tempcounter]='\0';
    fread(&(index_offsets[counter_index]),sizeof(long),1,txtfile);
    fread(&(index_lengths[counter_index]),sizeof(long),1,txtfile);
    counter_index++;
  } while(EOF!=fgetc(txtfile));

  //das ganze in .h-idxfile schreiben

  //h-file erzeugen
  idxfile=fopen(argv[2],"w");

  //allgemeine infos rein damit
  fprintf(idxfile,"//index-daten-include fÅr hugi xx...\n//einfach in hugi.c includen und neu compilieren\n//self-generated by a program ;)\n\n"
                  "long index_number=%lu;\n"
                  "char index_names[%lu][256]={",
                  counter_index,counter_index);

  //artikelnamen
  for(tempcounter=0;tempcounter<counter_index;tempcounter++)
  {
    fputc(34,idxfile);
    blahcounter=0;
    while( '\0'!=(tempchar=index_names[tempcounter][blahcounter]) )
    {
      if(34==tempchar)
      {
        fputc(92,idxfile);
      }
      fputc(tempchar,idxfile);
      blahcounter++;
    }
    fputc(34,idxfile);
    if(tempcounter!=counter_index-1) fputc(',',idxfile);
  }
  fprintf(idxfile,"};\nlong index_offsets[%lu]={",counter_index);

  //artikeloffsets
  for(tempcounter=0;tempcounter<counter_index;tempcounter++)
  {
    fprintf(idxfile,"%lu",index_offsets[tempcounter]);
    if(tempcounter!=counter_index-1) fputc(',',idxfile);
  }
  fprintf(idxfile,"};\nlong index_lengths[%lu]={",counter_index);

  //artikellengths
  for(tempcounter=0;tempcounter<counter_index;tempcounter++)
  {
    fprintf(idxfile,"%lu",index_lengths[tempcounter]);
    if(tempcounter!=counter_index-1) fputc(',',idxfile);
  }
  fprintf(idxfile,"};");

  //txtfile, idxfile schlie·en
  fclose(txtfile);
  fclose(idxfile);

  //speicher fÅr index_names freigeben
  for(tempcounter=0;tempcounter<200;tempcounter++)
    free(index_names[tempcounter]);
}